// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OneClick.Backend.Data;

#nullable disable

namespace OneClick.Backend.Migrations
{
    [DbContext(typeof(OneClickDbContext))]
    [Migration("20251227003551_CreateInitial")]
    partial class CreateInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OneClick.Shared.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Home & Garden"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sports"
                        });
                });

            modelBuilder.Entity("OneClick.Shared.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "15.6 inch, 8GB RAM, 256GB SSD",
                            ImageURL = "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&h=300&fit=crop",
                            Name = "Laptop HP",
                            Price = 899.99m,
                            Qty = 15
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Ergonomic design, 2.4GHz wireless",
                            ImageURL = "https://images.unsplash.com/photo-1527814050087-3793815479db?w=400&h=300&fit=crop",
                            Name = "Wireless Mouse",
                            Price = 25.50m,
                            Qty = 50
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Fast charging, 6ft length",
                            ImageURL = "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=400&h=300&fit=crop",
                            Name = "USB-C Cable",
                            Price = 12.99m,
                            Qty = 100
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "100% Cotton, Size M",
                            ImageURL = "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&h=300&fit=crop",
                            Name = "T-Shirt Blue",
                            Price = 19.99m,
                            Qty = 30
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Denim, Regular fit",
                            ImageURL = "https://images.unsplash.com/photo-1542272604-787c3835535d?w=400&h=300&fit=crop",
                            Name = "Jeans Classic",
                            Price = 49.99m,
                            Qty = 20
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Warm and waterproof",
                            ImageURL = "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400&h=300&fit=crop",
                            Name = "Winter Jacket",
                            Price = 89.99m,
                            Qty = 10
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "Complete guide for beginners",
                            ImageURL = "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&h=300&fit=crop",
                            Name = "C# Programming Guide",
                            Price = 35.00m,
                            Qty = 25
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Description = "By Robert C. Martin",
                            ImageURL = "https://images.unsplash.com/photo-1541963463532-d68292c34b19?w=400&h=300&fit=crop",
                            Name = "Clean Code",
                            Price = 42.50m,
                            Qty = 18
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Description = "Essential guide",
                            ImageURL = "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=300&fit=crop",
                            Name = "Design Patterns",
                            Price = 38.99m,
                            Qty = 22
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            Description = "12-cup programmable",
                            ImageURL = "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400&h=300&fit=crop",
                            Name = "Coffee Maker",
                            Price = 79.99m,
                            Qty = 12
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            Description = "5-piece essential set",
                            ImageURL = "https://images.unsplash.com/photo-1591727884967-5e6b8f19123c?w=400&h=300&fit=crop",
                            Name = "Garden Tools Set",
                            Price = 45.00m,
                            Qty = 8
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            Description = "Adjustable brightness",
                            ImageURL = "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=300&fit=crop",
                            Name = "LED Desk Lamp",
                            Price = 32.99m,
                            Qty = 35
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 5,
                            Description = "Non-slip, eco-friendly",
                            ImageURL = "https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?w=400&h=300&fit=crop",
                            Name = "Yoga Mat",
                            Price = 28.50m,
                            Qty = 40
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            Description = "5-25 lbs adjustable",
                            ImageURL = "https://images.unsplash.com/photo-1534367507877-0edd93bd013b?w=400&h=300&fit=crop",
                            Name = "Dumbbells Set",
                            Price = 120.00m,
                            Qty = 6
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 5,
                            Description = "Lightweight, Size 10",
                            ImageURL = "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=300&fit=crop",
                            Name = "Running Shoes",
                            Price = 85.00m,
                            Qty = 14
                        });
                });

            modelBuilder.Entity("OneClick.Shared.Entities.Product", b =>
                {
                    b.HasOne("OneClick.Shared.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("OneClick.Shared.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
