// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OneClick.Backend.Data;

#nullable disable

namespace OneClick.Backend.Migrations
{
    [DbContext(typeof(OneClickDbContext))]
    [Migration("20260408182334_InitialSetup")]
    partial class InitialSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("OneClick.Shared.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("OneClick.Shared.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Apple"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cars"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Beauty"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Footwear"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Food"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Cosmetics"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Erotic"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Hardware"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Gamer"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Home"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Garden"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Toys"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Lingerie"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Pets"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Nutrition"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Technology"
                        });
                });

            modelBuilder.Entity("OneClick.Shared.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ShippingName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShippingPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OneClick.Shared.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("OneClick.Shared.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name", "CategoryId")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Apple smartphone, 128GB",
                            ImageURL = "https://images.unsplash.com/photo-1695048133142-1a20484d2569?q=80&w=600",
                            Name = "iPhone 15",
                            Price = 899.00m,
                            Qty = 20
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Apple laptop, 8GB/256GB",
                            ImageURL = "https://images.unsplash.com/photo-1517336714731-489689fd1ca4?q=80&w=600",
                            Name = "MacBook Air 13 M2",
                            Price = 1199.00m,
                            Qty = 8
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Shampoo, wax and microfiber towels",
                            ImageURL = "https://images.unsplash.com/photo-1607860108855-64acf2078ed9?q=80&w=600",
                            Name = "Car Care Kit",
                            Price = 39.99m,
                            Qty = 35
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "1080p dashboard camera with loop recording",
                            ImageURL = "https://images.unsplash.com/photo-1590333746438-d81ff1590ce3?q=80&w=600",
                            Name = "Dash Cam HD",
                            Price = 69.99m,
                            Qty = 12
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Description = "Daily moisturizer for all skin types",
                            ImageURL = "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=600",
                            Name = "Hydrating Face Cream",
                            Price = 22.50m,
                            Qty = 40
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "Brightening 10% serum",
                            ImageURL = "https://images.unsplash.com/photo-1620916297397-a4a5402a3c6c?q=80&w=600",
                            Name = "Vitamin C Serum",
                            Price = 18.99m,
                            Qty = 15
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Description = "Lightweight breathable trainers",
                            ImageURL = "https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=600",
                            Name = "Men's Running Shoes",
                            Price = 79.90m,
                            Qty = 25
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Description = "Comfort everyday sneakers",
                            ImageURL = "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?q=80&w=600",
                            Name = "Women's Casual Sneakers",
                            Price = 59.90m,
                            Qty = 10
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            Description = "Whole-grain oats with nuts",
                            ImageURL = "https://images.unsplash.com/photo-1517093728432-a0440f8d45ca?q=80&w=600",
                            Name = "Organic Granola 500g",
                            Price = 6.99m,
                            Qty = 50
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            Description = "Extra virgin, cold pressed",
                            ImageURL = "https://images.unsplash.com/photo-1474979266404-7cadd259c308?q=80&w=600",
                            Name = "Olive Oil 1L",
                            Price = 9.99m,
                            Qty = 30
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 6,
                            Description = "Long-wear, natural shade",
                            ImageURL = "https://images.unsplash.com/photo-1586495777744-4413f21062fa?q=80&w=600",
                            Name = "Matte Lipstick",
                            Price = 12.99m,
                            Qty = 35
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 6,
                            Description = "Water-resistant, volume effect",
                            ImageURL = "https://images.unsplash.com/photo-1631214524020-7e18db9a8f92?q=80&w=600",
                            Name = "Black Mascara",
                            Price = 11.49m,
                            Qty = 22
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 7,
                            Description = "PU match ball",
                            ImageURL = "https://images.unsplash.com/photo-1614632537423-1e6c2e7e0aab?q=80&w=600",
                            Name = "Football Size 5",
                            Price = 29.99m,
                            Qty = 60
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 7,
                            Description = "Non-slip exercise mat",
                            ImageURL = "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?q=80&w=600",
                            Name = "Yoga Mat 6mm",
                            Price = 24.50m,
                            Qty = 8
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 8,
                            Description = "Scented candles set for ambience",
                            ImageURL = "https://images.unsplash.com/photo-1602826347632-009a584de633?q=80&w=600",
                            Name = "Romance Candle Set",
                            Price = 19.99m,
                            Qty = 25
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 8,
                            Description = "Couples card & board game",
                            ImageURL = "https://images.unsplash.com/photo-1632501641765-e568d28b0015?q=80&w=600",
                            Name = "Romantic Board Game",
                            Price = 17.50m,
                            Qty = 12
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 9,
                            Description = "2 batteries, fast charger",
                            ImageURL = "https://images.unsplash.com/photo-1504148455328-c376907d081c?q=80&w=600",
                            Name = "Cordless Drill 18V",
                            Price = 89.00m,
                            Qty = 14
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 9,
                            Description = "Sockets, bits and ratchet",
                            ImageURL = "https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?q=80&w=600",
                            Name = "Tool Set 46pcs",
                            Price = 39.99m,
                            Qty = 40
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 10,
                            Description = "Linear switches, full-size",
                            ImageURL = "https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?q=80&w=600",
                            Name = "Mechanical Keyboard RGB",
                            Price = 69.90m,
                            Qty = 18
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 10,
                            Description = "Programmable buttons",
                            ImageURL = "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?q=80&w=600",
                            Name = "Gaming Mouse 8K DPI",
                            Price = 29.90m,
                            Qty = 45
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 11,
                            Description = "Adjustable arm, warm/cool light",
                            ImageURL = "https://images.unsplash.com/photo-1534073828943-f801091a7d58?q=80&w=600",
                            Name = "LED Desk Lamp",
                            Price = 22.99m,
                            Qty = 45
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 11,
                            Description = "Ergonomic cervical pillow",
                            ImageURL = "https://images.unsplash.com/photo-1584100936595-c0654b55a2e6?q=80&w=600",
                            Name = "Memory Foam Pillow",
                            Price = 34.90m,
                            Qty = 16
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 12,
                            Description = "Flexible anti-kink hose",
                            ImageURL = "https://images.unsplash.com/photo-1596707328646-778832a8747f?q=80&w=600",
                            Name = "Garden Hose 15m",
                            Price = 19.99m,
                            Qty = 30
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 12,
                            Description = "Bypass pruner stainless steel",
                            ImageURL = "https://images.unsplash.com/photo-1622374274291-3e4b77f32997?q=80&w=600",
                            Name = "Pruning Shears",
                            Price = 12.50m,
                            Qty = 25
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 13,
                            Description = "Compatible bricks 500 pcs",
                            ImageURL = "https://images.unsplash.com/photo-1587654780291-39c940483713?q=80&w=600",
                            Name = "Building Blocks Set",
                            Price = 24.99m,
                            Qty = 40
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 13,
                            Description = "Landscape illustration",
                            ImageURL = "https://images.unsplash.com/photo-1610419885843-0c4a457493a7?q=80&w=600",
                            Name = "Puzzle 1000 Pieces",
                            Price = 14.99m,
                            Qty = 12
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 14,
                            Description = "Two-piece loungewear set",
                            ImageURL = "https://images.unsplash.com/photo-1594967384738-9e63e2621746?q=80&w=600",
                            Name = "Soft Sleepwear Set",
                            Price = 29.90m,
                            Qty = 28
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 14,
                            Description = "Comfort fit essentials",
                            ImageURL = "https://images.unsplash.com/photo-1596489392231-15b565780365?q=80&w=600",
                            Name = "Seamless Undergarments",
                            Price = 19.90m,
                            Qty = 18
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 15,
                            Description = "Chicken & rice formula",
                            ImageURL = "https://images.unsplash.com/photo-1589924691195-41432c84c161?q=80&w=600",
                            Name = "Dry Dog Food 3kg",
                            Price = 16.99m,
                            Qty = 35
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 15,
                            Description = "Sisal rope post with base",
                            ImageURL = "https://images.unsplash.com/photo-1545249390-6bdfa286032f?q=80&w=600",
                            Name = "Cat Scratching Post",
                            Price = 21.99m,
                            Qty = 14
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 16,
                            Description = "Vanilla flavor",
                            ImageURL = "https://images.unsplash.com/photo-1593095948071-474c5cc2989d?q=80&w=600",
                            Name = "Whey Protein 1kg",
                            Price = 32.90m,
                            Qty = 20
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 16,
                            Description = "Daily vitamins & minerals",
                            ImageURL = "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?q=80&w=600",
                            Name = "Multivitamin 120 caps",
                            Price = 14.50m,
                            Qty = 10
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 17,
                            Description = "Classic fit, 100% cotton",
                            ImageURL = "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?q=80&w=600",
                            Name = "Men's Cotton T-Shirt",
                            Price = 14.99m,
                            Qty = 60
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 17,
                            Description = "Mid-wash, regular fit",
                            ImageURL = "https://images.unsplash.com/photo-1551028719-00167b16eac5?q=80&w=600",
                            Name = "Women's Denim Jacket",
                            Price = 49.90m,
                            Qty = 9
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 18,
                            Description = "Portable speaker with mic",
                            ImageURL = "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?q=80&w=600",
                            Name = "Bluetooth Speaker",
                            Price = 34.99m,
                            Qty = 25
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 18,
                            Description = "HDMI, USB 3.0, SD/MicroSD",
                            ImageURL = "https://images.unsplash.com/photo-1630080644612-4b2eb00438a9?q=80&w=600",
                            Name = "USB-C Hub 6-in-1",
                            Price = 24.90m,
                            Qty = 15
                        });
                });

            modelBuilder.Entity("OneClick.Shared.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("OneClick.Shared.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("OneClick.Shared.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneClick.Shared.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("OneClick.Shared.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OneClick.Shared.Entities.CartItem", b =>
                {
                    b.HasOne("OneClick.Shared.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneClick.Shared.Entities.User", "User")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OneClick.Shared.Entities.Order", b =>
                {
                    b.HasOne("OneClick.Shared.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OneClick.Shared.Entities.OrderItem", b =>
                {
                    b.HasOne("OneClick.Shared.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneClick.Shared.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OneClick.Shared.Entities.Product", b =>
                {
                    b.HasOne("OneClick.Shared.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("OneClick.Shared.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("OneClick.Shared.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("OneClick.Shared.Entities.User", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
