// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OneClick.Backend.Data;

#nullable disable

namespace OneClick.Backend.Migrations
{
    [DbContext(typeof(OneClickDbContext))]
    [Migration("20260101152529_SeedMoreRealProducts")]
    partial class SeedMoreRealProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OneClick.Shared.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Apple"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cars"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Beauty"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Footwear"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Food"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Cosmetics"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Erotic"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Hardware"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Gamer"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Home"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Garden"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Toys"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Lingerie"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Pets"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Nutrition"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Technology"
                        });
                });

            modelBuilder.Entity("OneClick.Shared.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Titanium design, A17 Pro chip, 128GB.",
                            ImageURL = "https://images.unsplash.com/photo-1696446701796-da61225697cc?auto=format&fit=crop&w=600&h=600&q=80",
                            Name = "iPhone 15 Pro",
                            Price = 999.00m,
                            Qty = 20
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Supercharged by M2. 13.6-inch Liquid Retina display.",
                            ImageURL = "https://images.unsplash.com/photo-1517336714731-489689fd1ca4?auto=format&fit=crop&w=600&h=600&q=80",
                            Name = "MacBook Air M2",
                            Price = 1199.00m,
                            Qty = 8
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Ultimate protection and shine for your vehicle.",
                            ImageURL = "https://images.unsplash.com/photo-1601362840469-51e4d8d58785?auto=format&fit=crop&w=600&h=600&q=80",
                            Name = "Premium Car Wax",
                            Price = 24.99m,
                            Qty = 35
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Front and rear recording, night vision included.",
                            ImageURL = "https://images.unsplash.com/photo-1680519324888-03823798950c?auto=format&fit=crop&w=600&h=600&q=80",
                            Name = "4K Dash Cam",
                            Price = 89.50m,
                            Qty = 12
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Description = "24-hour hydration for sensitive skin.",
                            ImageURL = "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=600&h=600&q=80",
                            Name = "Hydrating Moisturizer",
                            Price = 32.00m,
                            Qty = 40
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "Brightens skin tone and reduces fine lines.",
                            ImageURL = "https://images.unsplash.com/photo-1620916297397-a4a5402a3c6c?auto=format&fit=crop&w=600&h=600&q=80",
                            Name = "Vitamin C Glow Serum",
                            Price = 45.00m,
                            Qty = 15
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Description = "Lightweight cushioning for long distance runs.",
                            ImageURL = "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&h=600&q=80",
                            Name = "Pro Running Shoes",
                            Price = 129.99m,
                            Qty = 25
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Description = "Classic white sneakers for everyday wear.",
                            ImageURL = "https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?auto=format&fit=crop&w=600&h=600&q=80",
                            Name = "Urban Sneakers",
                            Price = 79.90m,
                            Qty = 10
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            Description = "Organic honey, nuts, and oats blend.",
                            ImageURL = "https://images.unsplash.com/photo-1517093728432-a0440f8d45ca?auto=format&fit=crop&w=600&h=600&q=80",
                            Name = "Artisan Granola",
                            Price = 8.50m,
                            Qty = 50
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            Description = "Cold-pressed, imported from Italy.",
                            ImageURL = "https://images.unsplash.com/photo-1474979266404-7cadd259c308?auto=format&fit=crop&w=600&h=600&q=80",
                            Name = "Extra Virgin Olive Oil",
                            Price = 18.99m,
                            Qty = 30
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 6,
                            Description = "Long-lasting color with a creamy finish.",
                            ImageURL = "https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=600&h=600&q=80",
                            Name = "Velvet Matte Lipstick",
                            Price = 22.00m,
                            Qty = 35
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 6,
                            Description = "Waterproof formula for dramatic lashes.",
                            ImageURL = "https://images.unsplash.com/photo-1631214524020-7e18db9a8f92?auto=format&fit=crop&w=600&h=600&q=80",
                            Name = "Volume Mascara",
                            Price = 16.50m,
                            Qty = 22
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 7,
                            Description = "Official size and weight, high durability.",
                            ImageURL = "https://images.unsplash.com/photo-1614632537423-1e6c2e7e0aab?auto=format&fit=crop&w=600&h=600&q=80",
                            Name = "Pro Match Football",
                            Price = 34.99m,
                            Qty = 60
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 7,
                            Description = "Eco-friendly material with carrying strap.",
                            ImageURL = "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?auto=format&fit=crop&w=600&h=600&q=80",
                            Name = "Non-Slip Yoga Mat",
                            Price = 29.95m,
                            Qty = 8
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 8,
                            Description = "Set of 3 scented candles for relaxation.",
                            ImageURL = "https://images.unsplash.com/photo-1602826347632-009a584de633?auto=format&fit=crop&w=600&h=600&q=80",
                            Name = "Aromatherapy Candles",
                            Price = 24.99m,
                            Qty = 25
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 8,
                            Description = "Fun and romantic card game for date nights.",
                            ImageURL = "https://images.unsplash.com/photo-1630260655866-e3256037b605?auto=format&fit=crop&w=600&h=600&q=80",
                            Name = "Couples Board Game",
                            Price = 19.99m,
                            Qty = 12
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 9,
                            Description = "18V power with two rechargeable batteries.",
                            ImageURL = "https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=600&h=600&q=80",
                            Name = "Cordless Drill Set",
                            Price = 89.00m,
                            Qty = 14
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 9,
                            Description = "46-piece socket and wrench set.",
                            ImageURL = "https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?auto=format&fit=crop&w=600&h=600&q=80",
                            Name = "Mechanics Tool Kit",
                            Price = 45.00m,
                            Qty = 40
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 10,
                            Description = "Blue switches, fully customizable lighting.",
                            ImageURL = "https://images.unsplash.com/photo-1587829741301-dc798b91a602?auto=format&fit=crop&w=600&h=600&q=80",
                            Name = "RGB Mechanical Keyboard",
                            Price = 79.99m,
                            Qty = 18
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 10,
                            Description = "Ultra-lightweight, 16000 DPI sensor.",
                            ImageURL = "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=600&h=600&q=80",
                            Name = "Wireless Gaming Mouse",
                            Price = 49.99m,
                            Qty = 45
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 11,
                            Description = "LED with wireless charging base.",
                            ImageURL = "https://images.unsplash.com/photo-1534073828943-f801091a7d58?auto=format&fit=crop&w=600&h=600&q=80",
                            Name = "Modern Desk Lamp",
                            Price = 39.99m,
                            Qty = 45
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 11,
                            Description = "Memory foam for better neck support.",
                            ImageURL = "https://images.unsplash.com/photo-1584100936595-c0654b55a2e6?auto=format&fit=crop&w=600&h=600&q=80",
                            Name = "Ergonomic Pillow",
                            Price = 29.99m,
                            Qty = 16
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 12,
                            Description = "50ft flexible, kink-free water hose.",
                            ImageURL = "https://images.unsplash.com/photo-1596707328646-778832a8747f?auto=format&fit=crop&w=600&h=600&q=80",
                            Name = "Heavy Duty Hose",
                            Price = 27.50m,
                            Qty = 30
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 12,
                            Description = "Sharp stainless steel pruning shears.",
                            ImageURL = "https://images.unsplash.com/photo-1622374274291-3e4b77f32997?auto=format&fit=crop&w=600&h=600&q=80",
                            Name = "Garden Shears",
                            Price = 14.99m,
                            Qty = 25
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 13,
                            Description = "500-piece creative construction set.",
                            ImageURL = "https://images.unsplash.com/photo-1587654780291-39c940483713?auto=format&fit=crop&w=600&h=600&q=80",
                            Name = "Building Blocks Set",
                            Price = 39.95m,
                            Qty = 40
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 13,
                            Description = "1000-piece puzzle, landscape theme.",
                            ImageURL = "https://images.unsplash.com/photo-1610419885843-0c4a457493a7?auto=format&fit=crop&w=600&h=600&q=80",
                            Name = "Scenic Jigsaw Puzzle",
                            Price = 18.50m,
                            Qty = 12
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 14,
                            Description = "Soft and breathable 2-piece lounge set.",
                            ImageURL = "https://images.unsplash.com/photo-1594967384738-9e63e2621746?auto=format&fit=crop&w=600&h=600&q=80",
                            Name = "Silk Sleepwear Set",
                            Price = 55.00m,
                            Qty = 28
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 14,
                            Description = "Pack of 3 seamless undergarments.",
                            ImageURL = "https://images.unsplash.com/photo-1596489392231-15b565780365?auto=format&fit=crop&w=600&h=600&q=80",
                            Name = "Cotton Essentials Pack",
                            Price = 24.90m,
                            Qty = 18
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 15,
                            Description = "Chicken and brown rice formula, 5kg.",
                            ImageURL = "https://images.unsplash.com/photo-1589924691195-41432c84c161?auto=format&fit=crop&w=600&h=600&q=80",
                            Name = "Premium Dog Food",
                            Price = 42.99m,
                            Qty = 35
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 15,
                            Description = "Durable sisal rope with plush base.",
                            ImageURL = "https://images.unsplash.com/photo-1545249390-6bdfa286032f?auto=format&fit=crop&w=600&h=600&q=80",
                            Name = "Cat Scratching Post",
                            Price = 29.99m,
                            Qty = 14
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 16,
                            Description = "Chocolate flavor, 2lb tub.",
                            ImageURL = "https://images.unsplash.com/photo-1593095948071-474c5cc2989d?auto=format&fit=crop&w=600&h=600&q=80",
                            Name = "Isolate Whey Protein",
                            Price = 59.90m,
                            Qty = 20
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 16,
                            Description = "120 capsules, immunity support.",
                            ImageURL = "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&h=600&q=80",
                            Name = "Daily Multivitamin",
                            Price = 19.95m,
                            Qty = 10
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 17,
                            Description = "100% Organic cotton, regular fit.",
                            ImageURL = "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=600&h=600&q=80",
                            Name = "Classic White Tee",
                            Price = 19.99m,
                            Qty = 60
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 17,
                            Description = "Vintage wash, button-up front.",
                            ImageURL = "https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=600&h=600&q=80",
                            Name = "Denim Jacket",
                            Price = 64.90m,
                            Qty = 9
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 18,
                            Description = "Waterproof, 360-degree sound.",
                            ImageURL = "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=600&h=600&q=80",
                            Name = "Bluetooth Speaker",
                            Price = 49.99m,
                            Qty = 25
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 18,
                            Description = "7-in-1 connectivity for laptops.",
                            ImageURL = "https://images.unsplash.com/photo-1630080644612-4b2eb00438a9?auto=format&fit=crop&w=600&h=600&q=80",
                            Name = "USB-C Hub Adapter",
                            Price = 34.99m,
                            Qty = 15
                        });
                });

            modelBuilder.Entity("OneClick.Shared.Entities.Product", b =>
                {
                    b.HasOne("OneClick.Shared.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("OneClick.Shared.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
