// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OneClick.Backend.Data;

#nullable disable

namespace OneClick.Backend.Migrations
{
    [DbContext(typeof(OneClickDbContext))]
    [Migration("20260322015007_AddIdentitySecurity")]
    partial class AddIdentitySecurity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("OneClick.Shared.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("OneClick.Shared.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Apple"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cars"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Beauty"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Footwear"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Food"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Cosmetics"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Erotic"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Hardware"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Gamer"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Home"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Garden"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Toys"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Lingerie"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Pets"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Nutrition"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Technology"
                        });
                });

            modelBuilder.Entity("OneClick.Shared.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ShippingName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShippingPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OneClick.Shared.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("OneClick.Shared.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name", "CategoryId")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Titanium design, A17 Pro chip, the most powerful iPhone yet.",
                            ImageURL = "https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format=80",
                            Name = "iPhone 15 Pro Max",
                            Price = 1199.00m,
                            Qty = 20
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Supercharged by M2. Strikingly thin and fast.",
                            ImageURL = "https://images.unsplash.com/photo-1517336714731-489689fd1ca4?auto=format=80",
                            Name = "MacBook Air M2",
                            Price = 1099.00m,
                            Qty = 15
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Ultimate liquid wax for a deep mirror-like shine.",
                            ImageURL = "https://images.unsplash.com/photo-1601362840469-51e4d8d58785?auto=format=80",
                            Name = "Meguiar's Car Wax",
                            Price = 24.99m,
                            Qty = 50
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Secure your driving with 24/7 loop recording.",
                            ImageURL = "https://images.unsplash.com/photo-1680519324888-03823798950c?auto=format=80",
                            Name = "4K Dash Cam Front/Rear",
                            Price = 89.50m,
                            Qty = 12
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Description = "Instantly quenches dry skin for a healthy glow.",
                            ImageURL = "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format=80",
                            Name = "Hydro Boost Gel Cream",
                            Price = 19.99m,
                            Qty = 40
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "Brightening serum for uneven skin tone.",
                            ImageURL = "https://images.unsplash.com/photo-1620916297397-a4a5402a3c6c?auto=format=80",
                            Name = "Vitamin C Serum",
                            Price = 34.00m,
                            Qty = 25
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Description = "Responsive running shoes for road running.",
                            ImageURL = "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format=80",
                            Name = "Nike Air Zoom Pegasus",
                            Price = 129.99m,
                            Qty = 30
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Description = "Minimalist leather sneakers for everyday wear.",
                            ImageURL = "https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?auto=format=80",
                            Name = "Classic White Sneakers",
                            Price = 89.90m,
                            Qty = 18
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            Description = "Crunchy clusters with almonds and seeds.",
                            ImageURL = "https://images.unsplash.com/photo-1517093728432-a0440f8d45ca?auto=format=80",
                            Name = "Organic Honey Granola",
                            Price = 8.50m,
                            Qty = 60
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            Description = "Cold-pressed, rich flavor perfect for salads.",
                            ImageURL = "https://images.unsplash.com/photo-1474979266404-7cadd259c308?auto=format=80",
                            Name = "Extra Virgin Olive Oil",
                            Price = 18.99m,
                            Qty = 45
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 6,
                            Description = "Long-lasting color with a hydrating formula.",
                            ImageURL = "https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format=80",
                            Name = "Matte Velvet Lipstick",
                            Price = 22.00m,
                            Qty = 35
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 6,
                            Description = "Dramatic volume without clumping.",
                            ImageURL = "https://images.unsplash.com/photo-1631214524020-7e18db9a8f92?auto=format=80",
                            Name = "Volumizing Mascara",
                            Price = 16.50m,
                            Qty = 22
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 7,
                            Description = "FIFA quality certified ball size 5.",
                            ImageURL = "https://images.unsplash.com/photo-1614632537423-1e6c2e7e0aab?auto=format=80",
                            Name = "Pro Match Football",
                            Price = 34.99m,
                            Qty = 60
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 7,
                            Description = "Eco-friendly material with alignment lines.",
                            ImageURL = "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?auto=format=80",
                            Name = "Non-Slip Yoga Mat",
                            Price = 29.95m,
                            Qty = 15
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 8,
                            Description = "Set of 3 soy wax candles for ambiance.",
                            ImageURL = "https://images.unsplash.com/photo-1602826347632-009a584de633?auto=format=80",
                            Name = "Luxury Scented Candles",
                            Price = 24.99m,
                            Qty = 25
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 8,
                            Description = "Deepen your connection with fun questions.",
                            ImageURL = "https://images.unsplash.com/photo-1630260655866-e3256037b605?auto=format=80",
                            Name = "Couples Card Game",
                            Price = 19.99m,
                            Qty = 20
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 9,
                            Description = "18V power with 2 batteries and case.",
                            ImageURL = "https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format=80",
                            Name = "Cordless Drill Driver",
                            Price = 89.00m,
                            Qty = 14
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 9,
                            Description = "Socket wrench set for home and auto repair.",
                            ImageURL = "https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?auto=format=80",
                            Name = "46-Piece Tool Set",
                            Price = 45.00m,
                            Qty = 40
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 10,
                            Description = "Tactile blue switches with custom lighting.",
                            ImageURL = "https://images.unsplash.com/photo-1587829741301-dc798b91a602?auto=format=80",
                            Name = "RGB Mechanical Keyboard",
                            Price = 79.99m,
                            Qty = 18
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 10,
                            Description = "Ultra-lightweight, 20,000 DPI sensor.",
                            ImageURL = "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format=80",
                            Name = "Wireless Gaming Mouse",
                            Price = 49.99m,
                            Qty = 45
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 11,
                            Description = "Dimmable light with USB charging port.",
                            ImageURL = "https://images.unsplash.com/photo-1534073828943-f801091a7d58?auto=format=80",
                            Name = "Modern LED Desk Lamp",
                            Price = 39.99m,
                            Qty = 45
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 11,
                            Description = "Ergonomic cervical pillow for neck pain relief.",
                            ImageURL = "https://images.unsplash.com/photo-1584100936595-c0654b55a2e6?auto=format=80",
                            Name = "Memory Foam Pillow",
                            Price = 29.99m,
                            Qty = 16
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 12,
                            Description = "50ft flexible hose, leak-proof design.",
                            ImageURL = "https://images.unsplash.com/photo-1596707328646-778832a8747f?auto=format=80",
                            Name = "Expandable Garden Hose",
                            Price = 27.50m,
                            Qty = 30
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 12,
                            Description = "Sharp titanium blade for gardening.",
                            ImageURL = "https://images.unsplash.com/photo-1622374274291-3e4b77f32997?auto=format=80",
                            Name = "Professional Pruning Shears",
                            Price = 14.99m,
                            Qty = 25
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 13,
                            Description = "1000 pieces set, compatible with major brands.",
                            ImageURL = "https://images.unsplash.com/photo-1587654780291-39c940483713?auto=format=80",
                            Name = "Creative Building Blocks",
                            Price = 39.95m,
                            Qty = 40
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 13,
                            Description = "1000 pieces puzzle, high quality print.",
                            ImageURL = "https://images.unsplash.com/photo-1610419885843-0c4a457493a7?auto=format=80",
                            Name = "Landscape Jigsaw Puzzle",
                            Price = 18.50m,
                            Qty = 12
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 14,
                            Description = "Premium 2-piece pajama set.",
                            ImageURL = "https://images.unsplash.com/photo-1594967384738-9e63e2621746?auto=format=80",
                            Name = "Silk Satin Sleepwear",
                            Price = 55.00m,
                            Qty = 28
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 14,
                            Description = "Invisible underwear pack of 3.",
                            ImageURL = "https://images.unsplash.com/photo-1596489392231-15b565780365?auto=format=80",
                            Name = "Seamless Comfort Set",
                            Price = 24.90m,
                            Qty = 18
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 15,
                            Description = "Chicken & Brown Rice Recipe, 15 lbs.",
                            ImageURL = "https://images.unsplash.com/photo-1589924691195-41432c84c161?auto=format=80",
                            Name = "Premium Adult Dog Food",
                            Price = 42.99m,
                            Qty = 35
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 15,
                            Description = "Durable sisal pole with plush base.",
                            ImageURL = "https://images.unsplash.com/photo-1545249390-6bdfa286032f?auto=format=80",
                            Name = "Cat Scratching Post",
                            Price = 29.99m,
                            Qty = 14
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 16,
                            Description = "Chocolate flavor, 2 lbs, 25g protein.",
                            ImageURL = "https://images.unsplash.com/photo-1593095948071-474c5cc2989d?auto=format=80",
                            Name = "Whey Protein Isolate",
                            Price = 59.90m,
                            Qty = 20
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 16,
                            Description = "120 capsules, immunity & energy support.",
                            ImageURL = "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format=80",
                            Name = "Multivitamin Complex",
                            Price = 19.95m,
                            Qty = 10
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 17,
                            Description = "100% Organic cotton, slim fit.",
                            ImageURL = "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format=80",
                            Name = "Cotton Crew Neck T-Shirt",
                            Price = 19.99m,
                            Qty = 60
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 17,
                            Description = "Vintage wash, button closure.",
                            ImageURL = "https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format=80",
                            Name = "Classic Denim Jacket",
                            Price = 64.90m,
                            Qty = 9
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 18,
                            Description = "Waterproof IPX7, 360 sound, 12h battery.",
                            ImageURL = "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format=80",
                            Name = "Portable Bluetooth Speaker",
                            Price = 49.99m,
                            Qty = 25
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 18,
                            Description = "HDMI 4K, USB 3.0, SD Card Reader.",
                            ImageURL = "https://images.unsplash.com/photo-1630080644612-4b2eb00438a9?auto=format=80",
                            Name = "USB-C Hub 7-in-1",
                            Price = 34.99m,
                            Qty = 15
                        });
                });

            modelBuilder.Entity("OneClick.Shared.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "STATIC-CONCURRENCY-STAMP-1",
                            Email = "emilio@yopmail.com",
                            EmailConfirmed = true,
                            FirstName = "Emilio",
                            LastName = "Barrera",
                            LockoutEnabled = false,
                            NormalizedEmail = "EMILIO@YOPMAIL.COM",
                            NormalizedUserName = "EMILIO@YOPMAIL.COM",
                            PasswordHash = "123456",
                            PhoneNumberConfirmed = false,
                            Role = "Admin",
                            SecurityStamp = "STATIC-SECURITY-STAMP-1",
                            TwoFactorEnabled = false,
                            UserName = "emilio@yopmail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("OneClick.Shared.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("OneClick.Shared.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneClick.Shared.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("OneClick.Shared.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OneClick.Shared.Entities.CartItem", b =>
                {
                    b.HasOne("OneClick.Shared.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneClick.Shared.Entities.User", "User")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OneClick.Shared.Entities.Order", b =>
                {
                    b.HasOne("OneClick.Shared.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OneClick.Shared.Entities.OrderItem", b =>
                {
                    b.HasOne("OneClick.Shared.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneClick.Shared.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OneClick.Shared.Entities.Product", b =>
                {
                    b.HasOne("OneClick.Shared.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("OneClick.Shared.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("OneClick.Shared.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("OneClick.Shared.Entities.User", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
